# torchtitan Config.toml

[job]
dump_folder = "./outputs"
description = "Llama 3 debug training"
use_for_integration_test = true

[profiling]
enable_profiling = true
save_traces_folder = "profile_trace"
profile_freq = 10
enable_memory_snapshot = false
save_memory_snapshot_folder = "memory_snapshot"

[metrics]
log_freq = 1
enable_color_printing = true
enable_tensorboard = true
save_tb_folder = "tb"

[model]
name = "llama3"
norm_type = "rmsnorm"
tokenizer_path = "./test/assets/test_tiktoken.model"

[model.args]
dim = 768
n_layers = 12
n_heads = 6
n_kv_heads = 6
multiple_of = 128
ffn_dim_multiplier = 1.0
norm_eps = 1e-5
rope_theta = 500000.0
max_seq_len = 1024
ffn_scaling_fn = "s_curve_constrained"

[optimizer]
name = "AdamW"
lr = 8e-4

[training]
batch_size = 8
seq_len = 512
warmup_fraction = 0.0
stable_fraction = 0.6
max_norm = 1.0  # grad norm clipping
steps = 10
data_parallel_replicate_degree = 1
data_parallel_shard_degree = -1
tensor_parallel_degree = 1
compile = true
dataset = "c4_test"  # supported datasets: c4_test (2K), c4 (177M)
gradient_accumulation_steps = 4

[experimental]
context_parallel_degree = 1
pipeline_parallel_degree = 1
enable_async_tensor_parallel = false

[checkpoint]
enable_checkpoint = false
folder = "checkpoint"
interval_type = "steps"
interval = 5
model_weights_only = false
export_dtype = "float32"
async_mode = "disabled"  # ["disabled", "async", "async_with_pinned_mem"]

[activation_checkpoint]
mode = 'selective'  # ['none', 'selective', 'full']
selective_ac_option = '2'  # 'int' = ac every positive int layer or 'op', ac based on ops policy

[float8]
enable_float8_linear = false
