# torchtitan Config.toml
# NOTE: this toml config is a preset for 64 A100 GPUs.

[job]
dump_folder = "./outputs"
description = "Llama2 124m training"

[profiling]
enable_profiling = true
save_traces_folder = "profile_trace"
profile_freq = 100

[metrics]
log_freq = 10
enable_tensorboard = true
save_tb_folder = "tb"

[model]
name = "llama2"
norm_type = "rmsnorm"  # layernorm / np_layernorm / rmsnorm / fused_rmsnorm
tokenizer_path = "./torchtitan/datasets/tokenizer/llama2_tokenizer/tokenizer.model"

[model.args]
dim=768,
n_layers=12,
n_heads=6,
n_kv_heads=6,
multiple_of=128,
ffn_dim_multiplier=1.0,
norm_eps=1e-5,
rope_theta=500000.0,
max_seq_len=1024
ffn_scaling_fn="stepped"

[optimizer]
name = "AdamW"
lr = 1.8e-3

[training]
batch_size = 80
seq_len = 1024
warmup_fraction = 0.125
stable_fraction = 0.5
max_norm = 1.0  # grad norm clipping
steps = 8000
data_parallel_replicate_degree = 2
data_parallel_shard_degree = -1
tensor_parallel_degree = 1  # 8-way TP
compile = false
dataset = "fineweb"
seed = 42
gradient_accumulation_steps = 4

[experimental]
context_parallel_degree = 1
pipeline_parallel_degree = 1

[checkpoint]
enable_checkpoint = false
folder = "checkpoint"
interval_type = "steps"
interval = 500
model_weights_only = false
export_dtype = "float32"
async_mode = "disabled" # ["disabled", "async", "async_with_pinned_mem"]

[activation_checkpoint]
mode = 'full'

[float8]
enable_float8_linear = false
