# torchtitan Config.toml
# NOTE: this toml config is a preset for 64 A100 GPUs.

[job]
dump_folder = "./outputs"
description = "Llama2 124m training"

[profiling]
enable_profiling = true
save_traces_folder = "profile_trace"
profile_freq = 100

[metrics]
log_freq = 10
enable_tensorboard = true
save_tb_folder = "tb"

[model]
name = "llama2"
flavor = "124M"
norm_type = "rmsnorm"  # layernorm / np_layernorm / rmsnorm / fused_rmsnorm
tokenizer_path = "./torchtitan/datasets/tokenizer/llama2_tokenizer/tokenizer.model"

[optimizer]
name = "AdamW"
lr = 1.8e-3

[training]
batch_size = 32
seq_len = 1024
warmup_fraction = 0.125
stable_fraction = 0.4
max_norm = 1.0  # grad norm clipping
steps = 2000
data_parallel_replicate_degree = 1
data_parallel_shard_degree = 4
tensor_parallel_degree = 1  # 8-way TP
compile = true
dataset = "fineweb"
seed = 42
gradient_accumulation_steps = 4

[experimental]
context_parallel_degree = 1
pipeline_parallel_degree = 1

[checkpoint]
enable_checkpoint = false
folder = "checkpoint"
interval_type = "steps"
interval = 500
model_weights_only = false
export_dtype = "float32"
async_mode = "disabled" # ["disabled", "async", "async_with_pinned_mem"]

[activation_checkpoint]
mode = 'full'

[float8]
enable_float8_linear = false
